defmodule FastFood.Absinthe.Field do
  @moduledoc false

  @doc """
  Checks if given field should be marked non-null as GraphQL treats
  all fields as nullable by default.

  Field might be marked as non-null if any of the following happens:
  - it is manually whitelisted as non-null via ecto_schema's
    ff_non_null_fields function
  - it is a part of the primary key,
  - it is autogenerated on insert.
  """
  @spec is_non_null?(struct(), atom()) :: boolean()
  def is_non_null?(ecto_schema, field_name) do
    is_whitelisted =
      function_exported?(ecto_schema, :__fastfood__, 2) &&
        ecto_schema.__fastfood__(:non_null, field_name)

    is_primary_key =
      ecto_schema.__schema__(:primary_key)
      |> Enum.member?(field_name)

    is_autogenerated =
      ecto_schema.__schema__(:autogenerate_fields)
      |> Enum.member?(field_name)

    is_whitelisted || is_primary_key || is_autogenerated
  end
end
